import json
P = '/tmp/claude-0/qu'
r2A = json.load(open(P + '/explore2/args_A.json'))
known_r2 = r2A['known'].split('- OPEN Conjecture S2')[0]
known = known_r2 + """- Round-2 results (all proved and refereed unless marked). You may read the refereed round-2 proof files: /tmp/claude-0/qu/explore2/R2E1/proof_S2_partial.txt, R2E2/proof_S2_reduction.txt, R2E3/proof_S2_partial.txt, R2E5/proofs.txt, R2E6/proof_excess_asymptotics.txt, R2E7/proofs.txt, R2E8/proof_three_middle.txt (all under /tmp/claude-0/qu/explore2/), but not other files there.
- T9 thread criterion (R2E1): S2(i) [b in U, b == F (mod 2) => b+1 in U]; max U == 1+F (mod 2) when r divides no a_i; step-2 closure [b in U, b>=3 => b-2 in U]; U finite iff r divides no a_i.
- T10 (R2E2): S2 follows from three finite residue-level conditions TP_rho, E_rho, O_rho on the residue instance rho (part sizes never matter, by lifting). Proof file /tmp/claude-0/qu/explore2/R2E2/proof_S2_reduction.txt (you may read it). Statement: let r divide no a_i, rho = residue multiset, sigma = sum(rho_i-1), d = coefficients of A(1-q)/(1-q^r), tau = residue-class sums of (1-q)A, Q_u = d_u - tau_{u mod r}, ND(K): Q_{K-x} >= d_x for all x with K-r <= 2x < K, mu*_inf = max{u: f_u < tau_u} with f = coefficients of 1/((1-q)^{k-1}(1-q^r)); (TP) every z with Q^rho_z<0 has floor((sigma+1-2z)/r) even; (E) ND_rho(K) for all K == sigma+1 mod 2r with 2mu*_inf <= K <= sigma+1-2r; (O) ND_rho(K) for all K == sigma+1+r mod 2r with 2mu*_inf+3r <= K <= sigma+1-2r. Certificate verified for 3,154,273 residue multisets (r<=30). The k-independent strong version fails for 25,737/1,547,599 long rho.
- T11 (R2E3): U = [1,sigma] u {sigma+2, ..., tau*-2}, sigma == tau* == 1+F (mod 2); S2 <=> tau* <= sigma+4. Lemma 7 (PROVED): the residue-class sums Gamma_t of prod[a_i]_q are cyclically unimodal on Z/r, peaked at S/2 (S = D).
- T12 (R2E5): window lemma; all-equal a=[nr+s]^k (middle s): U = [1,kn+1] u (kn+1+E_inf) for n>=1, 4<=r<=30, 3<=k<=60; E_inf = {odd e<=E_odd} u {even e<=E_even}, E_odd<E_even (all r>=4).
- T13 (R2E6): E = B*-1-F satisfies |E - (c k - ln k/(r lambda))| <= C2 for fixed r and residue proportions with positive middle mass, a_min large; c = (sigma1-2theta*)/r, theta* root of (1+t)ln(1+t)-t ln t = L, L = max_j sum_s p_s ln|sin(pi j s/r)/sin(pi j/r)|, lambda = ln(1+1/theta*), sigma1 = sum p_s(s-1); 0<c<sigma1/r.
- T14 (R2E7): explicit L0 = max(1, floor((S-k+3-r)/2)) (S = sum(a_i-1)) suffices for the large-part regime (not sharp); U(a) c [1,F+1] u (F+U_inf); U_inf has two-chain structure; U_inf c [1,T6-F]. FALSE: 'U_inf has one of three shapes [1,T],[1,T]-{T-1},[1,T-2]' (r=10,k=40,T=15,U_inf=[1,11]).
- T15 (R2E8): exactly three a_i with middle residue (others residue 1 or r-1), r>=4: if r<=30 and nm<=37 (nm = #{a_i == -1 mod r}) then U = [1,B*], B* = T6 - 2*[tau_s<=-2 and s>=2mu], tau = (1-q)prod[rho_i]_q reduced mod q^r-1, mu = largest j in [1,r-1] with tau_j>0, s = (D+1) mod r. (Numerically 0 errors far beyond, incl. r up to 200 and nm>37.)
- Round-2 synthesis (proof refereed, ACCEPT), file /tmp/claude-0/qu/synth/r2/proof.txt (you MAY read this file): with delta = (1-q)A, a 'class pair' is 0<C<r with C == D+1 (mod 2); points x_n = (D+1-Z_n)/2, Z_n = C, 2r-C, 2r+C, 4r-C, ...; y_n = delta_{x_n}; A_n = y_0-y_1+...+(-1)^n y_n; a_n = (-1)^n A_n; n*(C) = least n with a_n<0; N* = min_C n*(C). Thm 3.1: P_b unimodal iff for every class pair the pair condition holds. Thm 4.2: if r divides no a_i, N* == F+1 (mod 2) and U = [1,N*] u {N*+2,...,beta}, beta = min_C beta_C, beta_C = largest b == F+1 with a_{b'-2}+y_{b'} >= 0 for all b' == F+1, b'<=b; N*+1 not in U; N*+2 in U iff |a_{N*}| <= y_{N*+2} for every pair with n*(C)=N*. Thm 4.7 window-centre dichotomy. S2 <=> beta <= N*+2.
- REFUTED (round-2 synthesis, exact, two implementations): the class-pair-LOCAL statement 'beta_C <= n*(C)+2 for every pair C' (this contains (Z2) of the structure-theorem route and the per-thread inequality L'). Counterexample r=8595, k=127, a_i in [1687,1693] (file /tmp/claude-0/qu/synth/r2/inst_ki_fail_r8595.txt): pair C=8594 has n*=3, beta_C=7, yet global U={1,2,3,5}. More: r=12552, r=15167 (F odd), r=50000. Pair-local failures in 42/1822 random instances with r in [2035,79838]; S2 itself held in all. Data for r<=400: no pair-local failure (hill-climb min ratio 1.02 at r=400). So any proof of S2 must combine different class pairs.
- A fast exact C implementation of the class-pair test exists: /tmp/claude-0/qu/synth/r2/c/ (s2check.c; read it, you may compile your own copy in your folder).
- OPEN: Conjecture S2 (only the odd shift b -> b-3 remains: B_off >= B*-3)."""
box = ("you may compute P (or anything derived from specific parameter values) ONLY in this region: "
       "(i) r<=120, k<=140, every a_i<=400, EXCLUDING (a) instances with exactly 4 or 5 middle residues (a_i mod r in [2,r-2]) whose other parts all have residue 1 or r-1, when k>=20; "
       "(b) instances with more than 50 parts of residue r-1, when k>=55; (c) instances whose parts take only two distinct values, both with middle residue, when k>=60; "
       "or (ii) r>=1000 (any k, any a_i). Everything with 121<=r<=999 is forbidden. "
       "For instances whose coefficients exceed 2^127 use the exact big-integer checker /tmp/claude-0/qu/tools/gt_big.py (profile(r,a,bs) -> list of bools) or your own exact implementation")
lit = r2A['lit'] + "\nRound-3 step-0 search: see the summary appended by the coordinator below (if present)."
paths_A = [
 {"id": "R3E1", "title": "Default: prove Conjecture S2 inside the class-pair framework by an argument that COMBINES different class pairs.",
  "instructions": "Start from Theorems 3.1/4.2 of the round-2 synthesis. The pair-local statement is false (r=8595), so find a cross-pair inequality: e.g. relate the pair C that fails at N* to its neighbours C±2 or to the pair attaining beta, using the cyclic unimodality of Gamma (T11 Lemma 7) or the identity sum of tau = 0. Goal: prove beta <= N*+2. Produce a step-by-step proof with numbered lemmas, or report FAILED with the exact obstruction and numbers (including any cross-pair inequality you tried and where it fails)."},
 {"id": "R3E2", "title": "Alternative: prove S2 via the residue certificate TP/E/O of T10, using the now-proved cyclic unimodality of class sums (T11 Lemma 7).",
  "instructions": "Do NOT work with class pairs of the full instance; work at the residue level rho (all parts < r) as in T10. Try to derive TP_rho, E_rho, O_rho for every rho from cyclic unimodality of prod[rho_i]_q mod (q^r-1) plus quantitative control of d, Q. Note the k-independent strong certificate is false, so k must enter. Prove, or report FAILED with numbers."},
 {"id": "R3E3", "title": "Alternative: prove S2 completely for each fixed small r (r=4, then 5, then 6) for ALL k and all a_i, by reduction to a finite computation plus an asymptotic regime.",
  "instructions": "For fixed r the residue data is a vector of counts (n_1..n_{r-1}). Use lifting (part sizes do not matter beyond L0) and the explicit structure of tau and of 1/((1-q)^{k-1}(1-q^r)) to show that for large counts the S2 inequalities hold with margin (asymptotic regime), and that the remaining finitely many count vectors can be checked by exact computation inside your box. Deliver: a theorem 'S2 holds for r=4' (and 5, 6 if reached) with proof + certificate scripts, or FAILED with where the reduction breaks."},
 {"id": "R3E4", "title": "Alternative: try to REFUTE Conjecture S2 globally at large r (r >= 1000, where pair-local failures exist).",
  "instructions": "Pair-local failures begin around r ~ 10^4 (42/1822 random instances in [2035,79838]). Search for an instance where the GLOBAL S2 fails (beta >= N*+4): tune instances so that the failing pair at N* is the only binding pair and its neighbours are slack; hill-climb on beta-N*; try r up to the largest you can compute exactly (C code with exact arithmetic or big ints). Verify any counterexample by brute force on the full coefficient list with an independent implementation. Report the counterexample, or the closest near-misses with numbers."},
]
paths_B = [
 {"id": "R3E5", "title": "Default: prove the three-middle closed form T15 for ALL r>=4 and ALL nm (remove r<=30, nm<=37).",
  "instructions": "T15's upper bound and residue reduction are general; the gap is the lower bound for the base family (m1,m2,m3,(r-1)^nm) when nm>=38 or r>=31. Find a structural argument (e.g. a peeling identity removing pairs of (r-1) factors, or an explicit formula for tau and the pair conditions in this family as functions of nm and r). Prove, or report FAILED with numbers."},
 {"id": "R3E6", "title": "Alternative: exactly FOUR middle residues: find a closed form for U (in terms of r, Gamma/tau, D, F and a bounded correction), or prove that no Gamma-level closed form exists.",
  "instructions": "Work only inside your box (note the exclusion (a): with exactly 4 middle residues and all other residues 1 or r-1 you may use k<=19 only; with other residues present any k<=140). State a candidate rule with free-parameter count, or a non-existence statement with a witness pair (same Gamma-level data, different U). Report all candidates tried."},
 {"id": "R3E7", "title": "Alternative: the SHARP stabilization threshold L0 (least L such that a_min >= L forces U = [1,F] u (F+U_inf)).",
  "instructions": "Either find an explicit formula for the sharp L0 (in terms of r, residues, k), or prove that it is NOT a function of the residue vector alone (exhibit two instances with the same residue vector and same a_min whose stabilization differs, with proof). Report candidates tried and numbers."},
 {"id": "R3E8", "title": "Alternative: fine structure of the excess E(k) = B*-1-F along families with fixed r and fixed residue proportions: is E(k) - (c k - kappa ln k) eventually periodic / finite-state in k, or genuinely irregular?",
  "instructions": "Use exact computation (stay inside your box: r<=120, k<=140, or r>=1000) with large parts (stabilized regime) and the residue-only criterion. Test eventual periodicity, finite-automaton descriptions, or a closed form for the O(1) term; or give evidence/proof of irregularity. Report rule files with fit range and free parameters, or FAILED with numbers."},
]
for name, paths in [('A', paths_A), ('B', paths_B)]:
    json.dump({"lit": lit, "known": known, "box": box, "dir": P + "/explore3", "paths": paths},
              open(P + f'/explore3/args_{name}.json', 'w'), ensure_ascii=False)
print(len(known), len(box))
