# Library of candidate aggregate features f(r,a) (a sorted tuple, may contain 1s).
# r and b are always part of every key; these are the extra features searched over.
from math import gcd
def _nt(a): return [x for x in a if x>1]
FEATS = {
 'k':        lambda r,a: len(a),
 'kn':       lambda r,a: len(_nt(a)),
 'k1':       lambda r,a: sum(1 for x in a if x==1),
 'res_ms':   lambda r,a: tuple(sorted(x%r for x in a)),
 'res_ms_nt':lambda r,a: tuple(sorted(x%r for x in _nt(a))),
 'F':        lambda r,a: sum(x//r for x in a),
 'D':        lambda r,a: sum(x-1 for x in a),
 'S2':       lambda r,a: sum(x*x-1 for x in a),
 'S4':       lambda r,a: sum(x**4-1 for x in a),
 'floor_ms': lambda r,a: tuple(sorted(x//r for x in a)),
 'has0':     lambda r,a: any(x%r==0 for x in a),
 'n0':       lambda r,a: sum(1 for x in a if x%r==0),
 'maxa':     lambda r,a: max(a),
 'mina_nt':  lambda r,a: min(_nt(a)) if _nt(a) else 0,
 'nbig':     lambda r,a: sum(1 for x in a if x>=r),
 'sumres':   lambda r,a: sum(x%r for x in _nt(a)),
 'nnzres':   lambda r,a: sum(1 for x in _nt(a) if x%r),
 'gcd_ms':   lambda r,a: tuple(sorted(gcd(x,r) for x in _nt(a))),
 'par':      lambda r,a: (sum(1 for x in a if x%2==0), sum(1 for x in _nt(a) if x%2)),
 'maxres':   lambda r,a: max([x%r for x in _nt(a)],default=-1),
 'minres_nz':lambda r,a: min([x%r for x in _nt(a) if x%r],default=-1),
 'small_ms': lambda r,a: tuple(x for x in a if 1<x<r),
 'bigres_ms':lambda r,a: tuple(sorted(x%r for x in a if x>=r)),
 'Fc':       lambda r,a: tuple(sum(x//r for x in a if x%r==c) for c in range(r)),
 'ndist':    lambda r,a: len(set(_nt(a))),
 'cap_ms':   lambda r,a: tuple(sorted(min(x,r) for x in _nt(a))),
 'sumsqres': lambda r,a: sum((x%r)**2 for x in _nt(a)),
 'maxfloor': lambda r,a: max(x//r for x in a),
 'Dpar':     lambda r,a: sum(x-1 for x in a)%2,
 'Dmodr':    lambda r,a: sum(x-1 for x in a)%r,
 'resinv_ms':lambda r,a: tuple(sorted(min(x%r,r-x%r) for x in _nt(a))),
 'M11':      lambda r,a: sum((x//r)*(x%r) for x in a),
 'M20':      lambda r,a: sum((x//r)**2 for x in a),
}
