import json
P = '/tmp/claude-0/qu'
r2 = json.load(open(P + '/synth/args_r2_final.json'))
E3 = P + '/explore3'
# round-2 passed list, minus the 'pending' wording for N2_three (it passed on the third review)
passed = []
for c in r2['passed']:
    c = dict(c)
    if c['id'] == 'N2_three':
        c['basis'] = '有限范围计算 — PASSED on third review (A PASS, B PASS) after definitions were added to the statement.'
    passed.append(c)
passed += [
 {"id": "S2-r2synth", "statement": "Round-2 synthesis (proof ACCEPT): class-pair criterion Thm 3.1; structure Thm 4.2: if r divides no a_i, N* == F+1 (mod 2), U = [1,N*] u {N*+2,...,beta}, N*+1 not in U; Thm 4.7 window-centre dichotomy; S2 <=> beta <= N*+2.", "proof_file": P + "/synth/r2/proof.txt", "basis": "已证明 (referee ACCEPT)"},
 {"id": "X_pairlocal", "statement": "The class-pair-local statement beta_C <= n*(C)+2 for every pair is FALSE: r=8595, k=127, a_i in [1687,1693], C=8594: n*=3, beta_C=7, global U={1,2,3,5}. Another: r=10331, k=142 (found by a reviewer).", "basis": "反例 (two reimplementers PASS)"},
 {"id": "T16", "statement": "(R3E3) S2 holds for r=4,5,6, every k, all part sizes: if r divides no a_i then U = [1,B*] or [1,B*]\\{B*-1}. Computer-assisted (Lemma 1: L' at n*(C) for every pair => S2; V bounds via roots of unity; operator lemmas on products of q-integers; covering certificates for k<=140; hand proofs for k>=141; residue certificate + Theorem R for r=5 k<=23 and r=6 k<=53). Errata: Lemma 9 general statement false for odd r (only r=4 form used).", "proof_file": E3 + "/R3E3/proof_S2_r456.txt", "basis": "已证明 (referee ACCEPT, all certificates independently reimplemented)"},
 {"id": "T15b", "statement": "(R3E5) T15 for ALL r>=4 and all nm: exactly three a_i of middle residue, others residue 1 or r-1, r dividing no a_i => U = [1,B*], B* = T6 - 2*[tau_s<=-2 and s>=2mu]. Non-computational proof.", "proof_file": E3 + "/R3E5/proof_T15_all.txt", "basis": "已证明 (referee ACCEPT)"},
 {"id": "T17", "statement": "(R3E6 Theorem N) For exactly four middle residues (others 1 or r-1), no function of (r,k,b,residue multiset,F,D,Gamma,sum a_i,prod a_i) decides unimodality. Witness r=20: a=(1,14,59,65,79,105,123) U=[1,20] vs a'=(3,14,21,59,65,79,205) U=[1,22]; mechanism: parts equal to 1 change k' = #{a_i>=2}.", "proof_file": E3 + "/R3E6/proof_nonexistence.txt", "basis": "反例/已证明 (referee ACCEPT)"},
 {"id": "T18", "statement": "(R3E7) Stability (U = [1,F] u (F+U_inf)) is preserved by lifting a part by r; sharp L0* is an up-ray threshold with L0* <= max(2, floor(Delta_{e2}/2)+r+1); hybrid test H(Z): stable(a) => H(Z(a)), L0_hyb <= L0*, L0_hyb <= max(s)+1 <= r; Thm 8: L0* is not a function of (r,k,S,tau) (r=7: s=(1,1,3,4,4,4,4,5,5) L0*=2 vs s'=(1,2,2,4,4,4,4,4,6) L0*=3); Thm 9: stabilization not determined by (residue multiset, a_min) (r=5: (2,7,8^7) stable vs (2,2,8^7) not).", "proof_file": E3 + "/R3E7/proof_L0.txt", "basis": "已证明 (referee ACCEPT)"},
 {"id": "T19", "statement": "(R3E8) Fine structure of the excess: Lemma 1 (some middle residue => l_1 = l_{r-1} > other l_j); Lemma 2 exact phase alignment; Theorem 4/Cor 5: for fixed r and block with a middle residue, k = m p, if X_1(k) = ck - kappa ln k + gamma_1(parity of S1+1) is eps0-far from odd integers then E(k) = 2 floor((X_1(k)-1)/2); Prop 6: E(k) - (ck - kappa ln k) and the increments are not eventually periodic.", "proof_file": E3 + "/R3E8/proof_fine_structure.txt", "basis": "已证明 (referee ACCEPT)"},
 {"id": "T20", "statement": "(R3E2) Residue certificate of T10: TP_rho holds for every rho; E_rho holds for every rho (ND_rho(K_j) for all even j); O_rho <=> r(N*(rho)+5) > sigma+1-2mu*_inf; O_rho is FALSE in general (r=57, rho=(1^37,6,7,9,15,18,20,22,23,25,26,27,28,30,33,37): mu*_inf=-16, 2mu*_inf+3r=139<=141=K_1); mechanism: padding with ones lowers mu*_inf. S2 still holds on lifts of that instance.", "proof_file": E3 + "/R3E2/proof_TPE.txt", "basis": "已证明 (referee ACCEPT) + 反例 (N3_Ocex: two reimplementers PASS)"},
 {"id": "T21", "statement": "(R3E1) Window form of S2 (Lemmas A1/A2): S2 iff some (N*+4)-window S_{n+4}(t) = Phi(L+r-t) - Phi(L+2r+t) - psi(t) is negative. Theorem B* (cross-pair transfer): under (H2) per-unit decay e(z+1) <= e^{-kappa/r} e(z) beyond L-r/2 and shape condition (K*), a binding pair anywhere forces beta <= N*+2. Theorem B / Cor C2: residue-level certificate eps = sum_{j>=2} j|beta_j|/beta_1 < 1 with R_j = prod_i sin(pi j a_i/r)/sin(pi j/r). Proposition D (obstruction): explicit palindromic log-concave sequences (D1: r=3, D=34, U={1,3,5}; D2: r=8, U={1,2,3,5,7}; D3: r=3, U=[1,18]u{20,22,24}) with e unimodal, Wintner sign pattern and cyclically unimodal Gamma violate S2 - so S2 needs quantitative product structure (decay rate). Errata: D1 formula alpha_{7+j}=8^{12-j}9^j (printed 8^{11-j} is a typo).", "proof_file": E3 + "/R3E1/proof_crosspair.txt", "basis": "已证明 (referee ACCEPT)"},
 {"id": "N3_four", "statement": "Four-middle rule rule_gen (depends only on r, tau, D, k'=#{a_i>=2}; U = [1,T6-2] plus T6-1 and/or T6 decided by about r window inequalities with generic f = coefficients of 1/((1-q)^{k'-1}(1-q^r)) and one j=0 test): 0 errors on 1,213,632 exhaustive instances r=4..10; reviewer A 48,081 new instances (r up to 400) 0 errors.", "basis": "有限范围计算 — A PASS, B PASS. Unproved (conjecture)."},
 {"id": "N3_stab", "statement": "Stabilization rule / Conjecture Q (stable(a) <=> H(Z(a))) and L0* = L0_hyb: 31,779/31,779 exhaustive (r<=8, k<=10); reviewers: >7M exact pairs 0 errors, Q held on 12,183 + 8,000 random instances, r up to 300, k up to 260.", "basis": "有限范围计算 — A PASS, B PASS. Q unproved (conjecture)."},
]
holdout = r2['holdout_summary'] + """
Round-2 synthesis rule (S2 pair form) on H4: 0/51,858.
Round-5 holdout H5 + H5b (hidden from round-3 explorers; 1,140 (r,a) tuples, 53,669 pairs in the largest domain; strata: r in {2,3} k 141-200; r 4-12 k 141-200; r in {127,150,180,210}; four middle residues r 6-24 k 20-100; five middle residues r 6-15 k 20-80; residue r-1 dominant k 60-160; two distinct middle values k 60-160; H5b: r in 307..900, k up to 80, a_i up to 1500, incl. three-middle):
- R3E5 three-middle closed form (all r, nm): 0/3,734 (domain; incl. H5b r up to 777).
- R3E6 four-middle rule_gen: 0/10,311; rule_simple: 0/10,311.
- R3E7 stabilization rule (H-domain): 0/53,669 (all 10 strata).
- R3E8 asymptotic rules rule_B / rule_asym: 0/171 each in their (small) domain, but 61 / 92 errors in the fit box -> 拟合表.
Round-3 explorers: no rule for S2 itself; R3E4 found no global S2 counterexample in 316,601 float evaluations (r in [1000,50000]); beta-N* always 0 or 2; best failure margin -1.135 levels at r=15167."""
failures = r2['failures'] + "\n\nROUND 3 failure records: read /tmp/claude-0/qu/explore3/failure_only.txt (verbatim, R3E1-R3E8). Key items: cross-pair witnesses (middle pair) fail 27/1498 at r<=120; S2 does not follow from qualitative ingredients (Prop D); missing step for an unconditional S2 proof is a large-deviation decay estimate for delta=(1-q)A at local rate >= kappa_0/r (kappa_0 ~ 1.9-4.4) beyond L-r/2, or Conjecture DLC (delta log-concave on its rising part; 0 violations in 1799 instances); residue certificate O_rho false (padding with ones), so the T10 route cannot prove S2 in general; the four-middle rule is unproved (needs [1,T6-2] c U, window sufficiency, g vs generic f); Conjecture Q / sharp L0 = L0_hyb unproved (hard step: a part of quotient exactly 1 vs infinite part); rotation-word closed form for E(k) proved only away from thresholds; r>=7 S2 not covered by R3E3's method (Remark 7 speculative)."
lit = r2['lit_items'] + "\nRound-3 literature (step 0 + recheck, verdict CORRECTED): /tmp/claude-0/qu/lit3/step0_r3.json and /tmp/claude-0/qu/review/r3/rX_result.json. New: Mao-Shi-Zhu arXiv:2609.23779 (2026-09-20) settles Almkvist's conjecture on prod_{k=1}^n (1-q^{rk})/(1-q^k) (unimodal iff r even or n>=11) by first differences + Fourier/roots-of-unity estimates (different family, method link); CIMSY's own verification box for Conj 5.4: k<=5, r<=6, max{a_i,b}<=15 (sufficiency only). Krason-Milewski arXiv:1905.11815 Ex 4.8: class sums of Gaussian polynomials need not be cyclically unimodal. No source states any round-2/3 claim for r>=4."
args = {"problem": r2['problem'], "passed": passed, "holdout_summary": holdout, "failures": failures, "lit_items": lit, "round": 3}
json.dump(args, open(P + '/synth/args_r3.json', 'w'), ensure_ascii=False)
print(len(json.dumps(args, ensure_ascii=False)))
