// 初等篇内容：开局手牌、构造算子、有名字的一元算子、入门卡组图鉴、新手任务。
// 想加新卡组，就在 CATALOG 里加一项，并至少写两种做法（其中一种要用到别的卡组）。
// 高等篇的内容在 src/domains/ 里，由 src/content.js 汇总。

import { R, isInt, ONE, NEG1, ZERO, TWO } from './math.js';
import { aff, powU, expU, logU } from './unary.js';

const isPow2 = n => n >= 1 && (n & (n - 1)) === 0;
const isSquare = n => n >= 0 && Number.isInteger(Math.sqrt(n));

// 开局手牌
export const START = ['c:0', 'c:1', 'b:add', 'm:extend', 'm:closure', 'm:inverse', 'm:compose', 'm:union', 'm:inter', 'm:reverse', 'm:fill'];

// 构造算子：作用在算子或卡组上的"高阶"算子
export const META = [
  {
    id: 'extend',
    name: '延展',
    sym: '⟳',
    usage: '单卡 ＋ 一元算子 → 卡组；只放一个二元算子 → 升级它',
    desc: '把一步动作一直重复下去。从一张单卡出发反复做一元算子，就得到一个卡组。只放一个二元算子时，重复它会得到更高一级的运算。',
  },
  {
    id: 'closure',
    name: '封闭',
    sym: '⟨⟩',
    usage: '单卡或卡组 ＋ 二元算子 → 卡组',
    desc: '从一些卡出发，用一个二元算子两两组合，把新得到的卡也放进来继续组合，直到再也得不到新卡。',
  },
  {
    id: 'inverse',
    name: '逆',
    sym: '⁻¹',
    usage: '只放一个算子',
    desc: '把一个算子倒过来做。',
  },
  {
    id: 'compose',
    name: '复合',
    sym: '∘',
    usage: '左右各放一个一元算子',
    desc: '把两个一元算子接起来：先做左边的，再做右边的。',
  },
  {
    id: 'union',
    name: '并',
    sym: '∪',
    usage: '左右各放一个卡组（或单卡）',
    desc: '把两个卡组合成一个。单卡会被当成只有一张卡的卡组。',
  },
  {
    id: 'inter',
    name: '交',
    sym: '∩',
    usage: '左右各放一个卡组（或单卡）',
    desc: '只留下两个卡组都有的卡。',
  },
  {
    id: 'reverse',
    name: '反推',
    sym: '↤',
    usage: '一边放一元算子，另一边放单卡或卡组',
    desc: '找出所有代入这个算子后会得到那张卡（或落进那个卡组）的输入。算子没有逆的时候，反推照样能用，只是得到的是一个卡组：x² 反推 4 得到 {−2, 2}。',
  },
  {
    id: 'fill',
    name: '填',
    sym: '⊞',
    usage: '一边放缺口卡；另一边空着就自动填，放卡组就手填',
    desc: '把一个缺口填成新世界：找到包含原来的世界、又能让那条法走通的最小世界。自己用现有的卡凑一个世界来填，奖励更高；没人填过的缺口叫"前沿"。',
  },
];

export const BIN_INFO = {
  add: { desc: '把两个数合起来。它是开局唯一的运算，其他运算都要从它变出来。' },
  sub: { desc: '加法倒过来做：a + b = c，那么 c − b = a。' },
  mul: { desc: '反复做加法：3 × 4 = 4 + 4 + 4。' },
  div: { desc: '乘法倒过来做：a × b = c，那么 c ÷ b = a。' },
  pow: { desc: '反复做乘法：2⁴ = 2 × 2 × 2 × 2。' },
  mod: { desc: '反复减去（负数就反复加上）同一个数，直到落在 0 到它减 1 之间，剩下的就是余数：17 mod 5 = 2，−17 mod 5 = 3。' },
  cat: { desc: '把两个向量并排放在一起，拼成一个矩阵。' },
};

// 有名字的一元算子（其他一元算子直接用公式当名字）
export const NAMED_UN = [
  { id: 'succ', name: '后继', f: aff(ONE, ONE) },
  { id: 'pred', name: '前驱', f: aff(ONE, NEG1) },
  { id: 'neg', name: '取反', f: aff(NEG1, ZERO) },
  { id: 'dbl', name: '翻倍', f: aff(TWO, ZERO) },
  { id: 'half', name: '减半', f: aff(R(1, 2), ZERO) },
  { id: 'id', name: '恒等', f: aff(ONE, ZERO) },
  { id: 'odd', name: null, f: aff(TWO, ONE) },
  { id: 'recip', name: '倒数', f: powU(NEG1) },
  { id: 'sq', name: '平方', f: powU(TWO) },
  { id: 'cube', name: '立方', f: powU(R(3)) },
  { id: 'sqrt', name: '开方', f: powU(R(1, 2)) },
  { id: 'exp2', name: '2 的乘方', f: expU(TWO) },
  { id: 'log2', name: '以 2 为底的对数', f: logU(TWO) },
  { id: 'sign', name: '正负交替', f: expU(NEG1) },
];

export const CHAPTERS = [
  { id: 1, title: '数数', desc: '从 0 和 1 出发，一张一张往后数。' },
  { id: 2, title: '负数与对称', desc: '给每个数找一个镜像。' },
  { id: 3, title: '奇与偶', desc: '整数分成两队。' },
  { id: 4, title: '分数', desc: '把 1 切开。' },
];

// 入门卡组。recipes 里每一项是 [左, 中, 右]：
//   c:值  b:二元算子  u:有名字的一元算子  m:构造算子  d:卡组
export const CATALOG = [
  {
    id: 'N',
    short: 'ℕ',
    name: '自然数',
    ch: 1,
    preview: '{0, 1, 2, 3, 4, …}',
    struct: '集合',
    note: '对 + 和 × 都封闭。但 ℕ 里没有负数，1 找不到能和它相加得 0 的卡，所以 (ℕ, +) 还不是群。',
    desc: '从 0 开始，一个接一个往后数。',
    hint: '从 0 出发，每一步都 +1。',
    has: x => isInt(x) && x.n >= 0,
    recipes: [
      ['c:0', 'm:extend', 'u:succ'],
      ['d:Np', 'm:union', 'c:0'],
      ['d:Np', 'b:sub', 'c:1'],
      ['d:P2', 'u:log2', null],
    ],
  },
  {
    id: 'Np',
    short: 'ℕ⁺',
    name: '正整数',
    ch: 1,
    preview: '{1, 2, 3, 4, …}',
    struct: '集合',
    note: '对 + 和 × 都封闭。没有 0，所以连加法的单位元都没有。',
    desc: '数东西时用的数：1 个、2 个、3 个……',
    hint: '和自然数只差一张卡。',
    has: x => isInt(x) && x.n >= 1,
    recipes: [
      ['c:1', 'm:extend', 'u:succ'],
      ['c:1', 'm:closure', 'b:add'],
      ['d:N', 'b:add', 'c:1'],
      ['d:NegZ', 'u:neg', null],
    ],
  },
  {
    id: 'Sq',
    short: '平方数',
    name: '平方数',
    ch: 1,
    preview: '{0, 1, 4, 9, 16, …}',
    struct: '集合',
    note: '两个平方数相乘还是平方数（4 × 9 = 36），相加就不一定了（1 + 4 = 5）。',
    desc: '整数自己乘自己得到的数。',
    hint: '让自然数里的每一张卡都做「平方」。',
    has: x => isInt(x) && isSquare(x.n),
    recipes: [
      ['d:N', 'u:sq', null],
      ['d:Z', 'u:sq', null],
    ],
  },
  {
    id: 'P2',
    short: '2ⁿ',
    name: '2 的幂',
    ch: 1,
    preview: '{1, 2, 4, 8, 16, …}',
    struct: '集合',
    note: '对 × 封闭（4 × 8 = 32）。但 2 的倒数 1/2 不在里面，所以 (2ⁿ, ×) 不是群。',
    desc: '从 1 开始不断翻倍。',
    hint: '从 1 出发，每一步都翻倍。',
    has: x => isInt(x) && isPow2(x.n),
    recipes: [
      ['c:1', 'm:extend', 'u:dbl'],
      ['d:N', 'u:exp2', null],
      ['d:P2z', 'm:inter', 'd:N'],
    ],
  },
  {
    id: 'NegZ',
    short: '负整数',
    name: '负整数',
    ch: 2,
    preview: '{…, −3, −2, −1}',
    struct: '集合',
    note: '对 + 封闭，对 × 不封闭：(−2) × (−3) = 6 跑到外面去了。',
    desc: '比 0 小的整数，正整数在镜子里的样子。',
    hint: '把正整数的每一张都「取反」。',
    has: x => isInt(x) && x.n <= -1,
    recipes: [
      ['d:Np', 'u:neg', null],
      ['c:0', 'b:sub', 'd:Np'],
      ['c:-1', 'm:extend', 'u:pred'],
    ],
  },
  {
    id: 'Z',
    short: 'ℤ',
    name: '整数',
    ch: 2,
    preview: '{…, −2, −1, 0, 1, 2, …}',
    struct: '群',
    groupOp: '+',
    note: '(ℤ, +) 是群：加法封闭，0 是单位元，每个 n 都有逆元 −n。',
    desc: '自然数加上负整数。',
    hint: '自然数缺了负数，把它们补上。',
    has: x => isInt(x),
    recipes: [
      ['d:N', 'm:union', 'd:NegZ'],
      ['d:N', 'm:closure', 'b:sub'],
      ['d:Even', 'm:union', 'd:Odd'],
      ['d:N', 'b:sub', 'd:N'],
      ['c:1', 'm:closure', 'b:sub'],
    ],
  },
  {
    id: 'Sign',
    short: '{±1}',
    name: '正负号',
    ch: 2,
    preview: '{−1, 1}',
    list: ['-1', '1'],
    struct: '群',
    groupOp: '×',
    note: '({±1}, ×) 是只有两个元素的群：1 是单位元，−1 的逆元就是它自己。',
    desc: '只有两张卡的小世界。',
    hint: '对 1 反复「取反」会怎样？',
    has: x => isInt(x) && Math.abs(x.n) === 1,
    recipes: [
      ['c:1', 'm:extend', 'u:neg'],
      ['c:-1', 'm:closure', 'b:mul'],
      ['d:Z', 'u:sign', null],
    ],
  },
  {
    id: 'Empty',
    short: '∅',
    name: '空集',
    ch: 2,
    preview: '{ }',
    list: [],
    struct: '集合',
    note: '一张卡都没有。它是所有卡组的子集。',
    desc: '两个卡组没有共同的卡时，交出来的就是它。',
    hint: '找两个没有共同卡的卡组，取「交」。',
    has: () => false,
    recipes: [
      ['d:Even', 'm:inter', 'd:Odd'],
      ['d:N', 'm:inter', 'd:NegZ'],
    ],
  },
  {
    id: 'Even',
    short: '偶数',
    name: '偶数',
    ch: 3,
    preview: '{…, −4, −2, 0, 2, 4, …}',
    struct: '群',
    groupOp: '+',
    note: '(偶数, +) 是群：偶数 + 偶数 还是偶数，0 是单位元，2 的逆元是 −2。',
    desc: '能被 2 整除的整数。',
    hint: '把每个整数都翻倍。',
    has: x => isInt(x) && x.n % 2 === 0,
    recipes: [
      ['d:Z', 'u:dbl', null],
      ['c:2', 'm:closure', 'b:sub'],
      ['d:Odd', 'b:add', 'c:1'],
      ['d:Odd', 'b:add', 'd:Odd'],
    ],
  },
  {
    id: 'Odd',
    short: '奇数',
    name: '奇数',
    ch: 3,
    preview: '{…, −3, −1, 1, 3, …}',
    struct: '集合',
    note: '奇数 + 奇数 = 偶数，对 + 不封闭，所以不是群；奇数 × 奇数 还是奇数。',
    desc: '偶数挪一步就是奇数。',
    hint: '偶数和它只差 1。',
    has: x => isInt(x) && Math.abs(x.n) % 2 === 1,
    recipes: [
      ['d:Even', 'b:add', 'c:1'],
      ['d:Z', 'u:odd', null],
      ['d:Even', 'b:sub', 'c:1'],
    ],
  },
  {
    id: 'Unit',
    short: '单位分数',
    name: '单位分数',
    ch: 4,
    preview: '{1, 1/2, 1/3, 1/4, …}',
    struct: '集合',
    note: '对 × 封闭：1/2 × 1/3 = 1/6。对 + 不封闭：1/2 + 1/3 = 5/6。',
    desc: '分子是 1 的分数。古埃及人记账就用它。',
    hint: '把正整数都「倒」过来。',
    has: x => x.n === 1,
    recipes: [
      ['d:Np', 'u:recip', null],
      ['c:1', 'b:div', 'd:Np'],
    ],
  },
  {
    id: 'Qp',
    short: 'ℚ⁺',
    name: '正有理数',
    ch: 4,
    preview: '{…, 1/2, 1, 3/2, 2, …}',
    struct: '群',
    groupOp: '×',
    note: '(ℚ⁺, ×) 是群：1 是单位元，a/b 的逆元是 b/a。',
    desc: '所有正的分数。',
    hint: '正整数 ÷ 正整数。',
    has: x => x.n > 0,
    recipes: [
      ['d:Np', 'b:div', 'd:Np'],
      ['d:Np', 'm:closure', 'b:div'],
      ['d:Unit', 'b:mul', 'd:Np'],
    ],
  },
  {
    id: 'P2z',
    short: '2ᶻ',
    name: '2 的整数次幂',
    ch: 4,
    preview: '{…, 1/4, 1/2, 1, 2, 4, …}',
    struct: '群',
    groupOp: '×',
    note: '(2ᶻ, ×) 是群：乘除都跑不出去，1 是单位元，2ⁿ 的逆元是 2⁻ⁿ。',
    desc: '2 的幂，再加上它们的倒数。',
    hint: '从 2 出发，乘法和除法随便用。',
    has: x => x.n > 0 && isPow2(x.n) && isPow2(x.d),
    recipes: [
      ['c:2', 'm:closure', 'b:div'],
      ['d:Z', 'u:exp2', null],
      ['d:P2', 'b:div', 'd:P2'],
    ],
  },
  {
    id: 'Q',
    short: 'ℚ',
    name: '有理数',
    ch: 4,
    preview: '{…, −1, −1/2, 0, 1/2, 1, …}',
    struct: '群',
    groupOp: '+',
    note: '(ℚ, +) 是群；去掉 0 以后，(ℚ∖{0}, ×) 也是群。它去掉 0 的样子会在第六章再遇到。',
    desc: '所有能写成 整数 ÷ 正整数 的数。',
    hint: '整数 ÷ 正整数。',
    has: () => true,
    recipes: [
      ['d:Z', 'b:div', 'd:Np'],
      ['d:Z', 'm:closure', 'b:div'],
      ['d:Qp', 'b:sub', 'd:Qp'],
    ],
  },
];

// 新手任务，按顺序完成
export const QUESTS = [
  {
    id: 'q1',
    title: '第一次合成',
    text: '依次点 1、加法、1，再按「合成」。',
    done: has => has('c:2'),
  },
  {
    id: 'q2',
    title: '把加法倒过来',
    text: '点「加法」，再点紫色的构造算子「逆」，然后合成。',
    done: has => has('b:sub'),
  },
  {
    id: 'q3',
    title: '留一个空位',
    text: '中间放「加法」，一边放 1，另一边空着。空位就是变量 x，你会得到一元算子 x + 1。',
    done: has => has('u:aff(1,1)'),
  },
  {
    id: 'q4',
    title: '第一个卡组',
    text: '左边放 0，中间放「延展」，右边放 x + 1。从 0 出发一直 +1，会得到什么？',
    done: has => has('d:N'),
  },
  {
    id: 'q4b',
    title: '第一个缺口',
    text: '把 ℕ 放进上面的「在……里」，左右都放 ℕ，中间放减法，合成。在 ℕ 里做减法，有一部分结果会跑出去：跑出去的就是缺口。',
    done: (has, ctx) => (ctx?.holes ?? 0) > 0,
  },
  {
    id: 'q4c',
    title: '填上它',
    text: '点缺口卡右上角的 i 打开详情，按「填」：得到图鉴里包含 ℕ 和负整数、又能做减法的最小世界。也可以自己凑一个卡组，和缺口一起放进合成台、中间放「填」来手填，奖励更高。',
    done: (has, ctx) => (ctx?.filled ?? 0) > 0,
  },
  {
    id: 'q4d',
    title: '反过来想',
    text: '先做出偶数：左边放 2，中间放「封闭」，右边放减法（从 2 出发反复相减）。再把中间换成「反推」，一边放 x + 1，另一边放偶数：哪些数加 1 以后会变成偶数？没有逆的算子也能反推，得到的是一个卡组。',
    done: has => has('d:Odd'),
  },
  {
    id: 'q5',
    title: '集齐入门卡组',
    text: '打开「图鉴」，每个卡组都有提示。每个卡组都能用别的卡组造出来，试着多找几种做法。',
    done: has => CATALOG.every(c => has(`d:${c.id}`)),
  },
];
