// Verify Conjecture 3.9 at size N assuming it holds for all sizes < N.
// Minimal-counterexample argument: if |RP(w)|<=2 then (Remark 3.4 + dihedral
// symmetry) deleting value N, value 1, the first entry, or the last entry gives
// permutations with |RP|<=2, hence skew-merged by induction.  So it suffices to
// compute |RP| for every non-skew-merged w in S_N all of whose four extremal
// deletions are skew-merged ("candidates").  We enumerate them as insertions of N
// into skew-merged u in S_{N-1} (skew-merged perms generated by max-insertion).
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef unsigned long long u64;
u64 rp1(int n, const int *w);
// ok[p]=1 iff inserting a new maximum into u (length k, distinct values) before index p avoids 3412/2143
static void insok(const int *u, int k, char *ok){
  for(int p=0;p<=k;p++){
    int pm=-1; for(int a=0;a<p;a++) if(u[a]>pm) pm=u[a];
    int c1=0;
    if(pm>=0){ int mn=1<<30; for(int d=p; d<k; d++){ if(mn<u[d] && u[d]<pm){c1=1;break;} if(u[d]<mn) mn=u[d]; } }
    int c2=0;
    if(!c1){ int sm=-1; for(int d=p;d<k;d++) if(u[d]>sm) sm=u[d];
      if(sm>=0){ int mn=1<<30; // scan a from p-1 down: track min of u[b] for b in (a,p)
        for(int a=p-1;a>=0;a--){ if(mn<u[a] && u[a]<sm){c2=1;break;} if(u[a]<mn) mn=u[a]; } } }
    ok[p]=!(c1||c2);
  }
}
static int N; static u64 nskew=0, ncand=0, nsmall=0, minrp=~0ULL; static u64 hist[64];
static int perm[32];
static void leaf(int *u){ // u has length N-1, values 0..N-2, skew-merged
  int k=N-1; char ok[32], okf[32], okl[32], ok1[32];
  insok(u,k,ok);
  int uf[32],ul[32],u1[32]; int q=-1;
  for(int i=1;i<k;i++) uf[i-1]=u[i];
  for(int i=0;i<k-1;i++) ul[i]=u[i];
  int t=0; for(int i=0;i<k;i++){ if(u[i]==0){q=i;continue;} u1[t++]=u[i]; }
  insok(uf,k-1,okf); insok(ul,k-1,okl); insok(u1,k-1,ok1);
  for(int p=0;p<=k;p++){
    if(ok[p]){ nskew++; continue; }
    int a = (p==0)? 1 : okf[p-1];
    int b = (p==k)? 1 : okl[p];
    int c = (p<=q)? ok1[p] : ok1[p-1];
    if(!(a&&b&&c)) continue;
    ncand++;
    int w[32]; int s=0; for(int i=0;i<p;i++) w[s++]=u[i]; w[s++]=N-1; for(int i=p;i<k;i++) w[s++]=u[i];
    u64 r=rp1(N,w); if(r<minrp) minrp=r; if(r<64) hist[r]++;
    if(r<=2){ nsmall++; printf("COUNTEREXAMPLE to 3.9: "); for(int i=0;i<N;i++) printf("%d ",w[i]+1); printf(" rp=%llu\n",r); fflush(stdout); }
  }
}
static void gen(int *u, int k){ // u skew-merged of length k (values 0..k-1)
  if(k==N-1){ leaf(u); return; }
  char ok[32]; insok(u,k,ok);
  int w[32];
  for(int p=0;p<=k;p++){ if(!ok[p]) continue;
    int s=0; for(int i=0;i<p;i++) w[s++]=u[i]; w[s++]=k; for(int i=p;i<k;i++) w[s++]=u[i];
    gen(w,k+1); }
}
int main(int argc,char**argv){
  N=atoi(argv[1]);
  int u[1]={0}; gen(u,1);
  printf("N=%d skew-merged(N)=%llu candidates=%llu min|RP| over candidates=%llu  #candidates with |RP|<=2: %llu\n",N,nskew,ncand,minrp,nsmall);
  printf("candidate |RP| histogram (<64):"); for(int r=0;r<64;r++) if(hist[r]) printf(" %d:%llu",r,hist[r]); printf("\n");
}
